Updated CI/CD Configuration files

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -4,9 +4,38 @@ phases:
   install:
     commands:
       - echo "Installing dependencies"
+
+  pre_build:
+    commands:
+      - echo "========================================="
+      - echo "Extracting Build Version"
+      - echo "========================================="
+
+      - echo "GIT_TAG=${GIT_TAG}"
+
+      - |
+        if [ -z "$GIT_TAG" ]; then
+          echo "ERROR: GIT_TAG is empty."
+          exit 1
+        fi
+
+      # Remove only the 'vp' prefix
+      - VERSION="${GIT_TAG#vp}"
+
+      - |
+        if [ -z "$VERSION" ] || [ "$VERSION" = "$GIT_TAG" ]; then
+          echo "ERROR: Invalid production tag."
+          exit 1
+        fi
+
+      - echo "$VERSION" > build_version.txt
+
+      - echo "Build Version:"
+      - cat build_version.txt
+
   build:
     commands:
-      - echo "Build phase"
+      - echo "Preparing deployment artifact..."
       - chmod +x script/*.sh
 
 artifacts:
