Updated CI/CD configuration files for Stage and Prod

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -13,8 +13,16 @@ phases:
 
       # Debug Information
       - echo "GIT_TAG=${GIT_TAG}"
+      - echo "APP_ENV=${APP_ENV}"
       - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"
       - echo "CODEBUILD_RESOLVED_SOURCE_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}"
+
+      # Validate APP_ENV
+      - |
+        if [ -z "$APP_ENV" ]; then
+          echo "ERROR: APP_ENV environment variable is empty."
+          exit 1
+        fi
 
       # Validate GIT_TAG
       - |
@@ -25,12 +33,19 @@ phases:
 
       # Extract Version
       - |
-        VERSION="${GIT_TAG#v}"
+        if [ "$APP_ENV" = "stage" ]; then
+          VERSION="${GIT_TAG#vs}"
+        elif [ "$APP_ENV" = "production" ]; then
+          VERSION="${GIT_TAG#vp}"
+        else
+          echo "ERROR: Invalid APP_ENV: $APP_ENV"
+          exit 1
+        fi
 
       # Validate extracted version
       - |
         if [ -z "$VERSION" ] || [ "$VERSION" = "$GIT_TAG" ]; then
-          echo "ERROR: Invalid tag format for production"
+          echo "ERROR: Invalid tag format for $APP_ENV."
           exit 1
         fi
 
